// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldServer;

namespace WorldServer.Migrations
{
    [DbContext(typeof(WorldDbContext))]
    [Migration("20180908221649_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WorldServer.Entities.WorldEntity", b =>
                {
                    b.Property<int>("ChunkX");

                    b.Property<int>("ChunkY");

                    b.Property<byte>("X");

                    b.Property<byte>("Y");

                    b.Property<short>("EntityId");

                    b.Property<string>("Payload");

                    b.HasKey("ChunkX", "ChunkY", "X", "Y");

                    b.HasIndex("ChunkX", "ChunkY");

                    b.ToTable("entity");
                });
#pragma warning restore 612, 618
        }
    }
}
