// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorldServer.Database;

namespace WorldServer.Migrations
{
    [DbContext(typeof(WorldContext))]
    partial class WorldContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.3-rtm-32065");

            modelBuilder.Entity("WorldServer.Entities.WorldEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(128);

                    b.Property<int>("ChunkX");

                    b.Property<int>("ChunkY");

                    b.Property<string>("Json");

                    b.Property<byte>("X");

                    b.Property<byte>("Y");

                    b.Property<string>("type")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ChunkX", "ChunkY");

                    b.ToTable("WorldEntity");

                    b.HasDiscriminator<string>("type").HasValue("WorldEntity");
                });

            modelBuilder.Entity("WorldServer.Entities.GameEntity<WorldServer.ValueObjects.City>", b =>
                {
                    b.HasBaseType("WorldServer.Entities.WorldEntity");


                    b.ToTable("GameEntity<City>");

                    b.HasDiscriminator().HasValue("city");
                });

            modelBuilder.Entity("WorldServer.Entities.GameEntity<WorldServer.ValueObjects.Player>", b =>
                {
                    b.HasBaseType("WorldServer.Entities.WorldEntity");


                    b.ToTable("GameEntity<Player>");

                    b.HasDiscriminator().HasValue("player");
                });
#pragma warning restore 612, 618
        }
    }
}
