namespace Tgl.Net.Bindings
{
    public enum FramebufferStatus : uint
    {
        GL_FRAMEBUFFER_COMPLETE = 36053,
        GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 36054,
        GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 36055,
        GL_FRAMEBUFFER_UNSUPPORTED = 36061
    }
}