namespace Tgl.Net.Bindings
{
    public enum RenderbufferParameterName : uint
    {
        GL_RENDERBUFFER_WIDTH = 36162,
        GL_RENDERBUFFER_HEIGHT = 36163,
        GL_RENDERBUFFER_INTERNAL_FORMAT = 36164,
        GL_RENDERBUFFER_RED_SIZE = 36176,
        GL_RENDERBUFFER_GREEN_SIZE = 36177,
        GL_RENDERBUFFER_BLUE_SIZE = 36178,
        GL_RENDERBUFFER_ALPHA_SIZE = 36179,
        GL_RENDERBUFFER_DEPTH_SIZE = 36180,
        GL_RENDERBUFFER_STENCIL_SIZE = 36181
    }
}