namespace Tgl.Net.Bindings
{
    public enum VertexAttribEnum : uint
    {
        GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 34975,
        GL_VERTEX_ATTRIB_ARRAY_ENABLED = 34338,
        GL_VERTEX_ATTRIB_ARRAY_SIZE = 34339,
        GL_VERTEX_ATTRIB_ARRAY_STRIDE = 34340,
        GL_VERTEX_ATTRIB_ARRAY_TYPE = 34341,
        GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 34922,
        GL_CURRENT_VERTEX_ATTRIB = 34342
    }
}