using System.Collections.Generic;
using System.Text;

namespace Game.Abstractions.Constants
{
    public enum KeyCode
    {
        UNKNOWN = 0,

        RETURN = '\r',
        ESCAPE = 27, // '\033'
        BACKSPACE = '\b',
        TAB = '\t',
        SPACE = ' ',
        EXCLAIM = '!',
        QUOTEDBL = '"',
        HASH = '#',
        PERCENT = '%',
        DOLLAR = '$',
        AMPERSAND = '&',
        QUOTE = '\'',
        LEFTPAREN = '(',
        RIGHTPAREN = ')',
        ASTERISK = '*',
        PLUS = '+',
        COMMA = ',',
        MINUS = '-',
        PERIOD = '.',
        SLASH = '/',
        NUM_0 = '0',
        NUM_1 = '1',
        NUM_2 = '2',
        NUM_3 = '3',
        NUM_4 = '4',
        NUM_5 = '5',
        NUM_6 = '6',
        NUM_7 = '7',
        NUM_8 = '8',
        NUM_9 = '9',
        COLON = ':',
        SEMICOLON = ';',
        LESS = '<',
        EQUALS = '=',
        GREATER = '>',
        QUESTION = '?',
        AT = '@',
        /*
        Skip uppercase letters
        */
        LEFTBRACKET = '[',
        BACKSLASH = '\\',
        RIGHTBRACKET = ']',
        CARET = '^',
        UNDERSCORE = '_',
        BACKQUOTE = '`',
        a = 'a',
        b = 'b',
        c = 'c',
        d = 'd',
        e = 'e',
        f = 'f',
        g = 'g',
        h = 'h',
        i = 'i',
        j = 'j',
        k = 'k',
        l = 'l',
        m = 'm',
        n = 'n',
        o = 'o',
        p = 'p',
        q = 'q',
        r = 'r',
        s = 's',
        t = 't',
        u = 'u',
        v = 'v',
        w = 'w',
        x = 'x',
        y = 'y',
        z = 'z',

        CAPSLOCK = (int)ScanCode.SCANCODE_CAPSLOCK | InputConstants.SCANCODE_MASK,

        F1 = (int)ScanCode.SCANCODE_F1 | InputConstants.SCANCODE_MASK,
        F2 = (int)ScanCode.SCANCODE_F2 | InputConstants.SCANCODE_MASK,
        F3 = (int)ScanCode.SCANCODE_F3 | InputConstants.SCANCODE_MASK,
        F4 = (int)ScanCode.SCANCODE_F4 | InputConstants.SCANCODE_MASK,
        F5 = (int)ScanCode.SCANCODE_F5 | InputConstants.SCANCODE_MASK,
        F6 = (int)ScanCode.SCANCODE_F6 | InputConstants.SCANCODE_MASK,
        F7 = (int)ScanCode.SCANCODE_F7 | InputConstants.SCANCODE_MASK,
        F8 = (int)ScanCode.SCANCODE_F8 | InputConstants.SCANCODE_MASK,
        F9 = (int)ScanCode.SCANCODE_F9 | InputConstants.SCANCODE_MASK,
        F10 = (int)ScanCode.SCANCODE_F10 | InputConstants.SCANCODE_MASK,
        F11 = (int)ScanCode.SCANCODE_F11 | InputConstants.SCANCODE_MASK,
        F12 = (int)ScanCode.SCANCODE_F12 | InputConstants.SCANCODE_MASK,

        PRINTSCREEN = (int)ScanCode.SCANCODE_PRINTSCREEN | InputConstants.SCANCODE_MASK,
        SCROLLLOCK = (int)ScanCode.SCANCODE_SCROLLLOCK | InputConstants.SCANCODE_MASK,
        PAUSE = (int)ScanCode.SCANCODE_PAUSE | InputConstants.SCANCODE_MASK,
        INSERT = (int)ScanCode.SCANCODE_INSERT | InputConstants.SCANCODE_MASK,
        HOME = (int)ScanCode.SCANCODE_HOME | InputConstants.SCANCODE_MASK,
        PAGEUP = (int)ScanCode.SCANCODE_PAGEUP | InputConstants.SCANCODE_MASK,
        DELETE = 127,
        END = (int)ScanCode.SCANCODE_END | InputConstants.SCANCODE_MASK,
        PAGEDOWN = (int)ScanCode.SCANCODE_PAGEDOWN | InputConstants.SCANCODE_MASK,
        RIGHT = (int)ScanCode.SCANCODE_RIGHT | InputConstants.SCANCODE_MASK,
        LEFT = (int)ScanCode.SCANCODE_LEFT | InputConstants.SCANCODE_MASK,
        DOWN = (int)ScanCode.SCANCODE_DOWN | InputConstants.SCANCODE_MASK,
        UP = (int)ScanCode.SCANCODE_UP | InputConstants.SCANCODE_MASK,

        NUMLOCKCLEAR = (int)ScanCode.SCANCODE_NUMLOCKCLEAR | InputConstants.SCANCODE_MASK,
        KP_DIVIDE = (int)ScanCode.SCANCODE_KP_DIVIDE | InputConstants.SCANCODE_MASK,
        KP_MULTIPLY = (int)ScanCode.SCANCODE_KP_MULTIPLY | InputConstants.SCANCODE_MASK,
        KP_MINUS = (int)ScanCode.SCANCODE_KP_MINUS | InputConstants.SCANCODE_MASK,
        KP_PLUS = (int)ScanCode.SCANCODE_KP_PLUS | InputConstants.SCANCODE_MASK,
        KP_ENTER = (int)ScanCode.SCANCODE_KP_ENTER | InputConstants.SCANCODE_MASK,
        KP_1 = (int)ScanCode.SCANCODE_KP_1 | InputConstants.SCANCODE_MASK,
        KP_2 = (int)ScanCode.SCANCODE_KP_2 | InputConstants.SCANCODE_MASK,
        KP_3 = (int)ScanCode.SCANCODE_KP_3 | InputConstants.SCANCODE_MASK,
        KP_4 = (int)ScanCode.SCANCODE_KP_4 | InputConstants.SCANCODE_MASK,
        KP_5 = (int)ScanCode.SCANCODE_KP_5 | InputConstants.SCANCODE_MASK,
        KP_6 = (int)ScanCode.SCANCODE_KP_6 | InputConstants.SCANCODE_MASK,
        KP_7 = (int)ScanCode.SCANCODE_KP_7 | InputConstants.SCANCODE_MASK,
        KP_8 = (int)ScanCode.SCANCODE_KP_8 | InputConstants.SCANCODE_MASK,
        KP_9 = (int)ScanCode.SCANCODE_KP_9 | InputConstants.SCANCODE_MASK,
        KP_0 = (int)ScanCode.SCANCODE_KP_0 | InputConstants.SCANCODE_MASK,
        KP_PERIOD = (int)ScanCode.SCANCODE_KP_PERIOD | InputConstants.SCANCODE_MASK,

        APPLICATION = (int)ScanCode.SCANCODE_APPLICATION | InputConstants.SCANCODE_MASK,
        POWER = (int)ScanCode.SCANCODE_POWER | InputConstants.SCANCODE_MASK,
        KP_EQUALS = (int)ScanCode.SCANCODE_KP_EQUALS | InputConstants.SCANCODE_MASK,
        F13 = (int)ScanCode.SCANCODE_F13 | InputConstants.SCANCODE_MASK,
        F14 = (int)ScanCode.SCANCODE_F14 | InputConstants.SCANCODE_MASK,
        F15 = (int)ScanCode.SCANCODE_F15 | InputConstants.SCANCODE_MASK,
        F16 = (int)ScanCode.SCANCODE_F16 | InputConstants.SCANCODE_MASK,
        F17 = (int)ScanCode.SCANCODE_F17 | InputConstants.SCANCODE_MASK,
        F18 = (int)ScanCode.SCANCODE_F18 | InputConstants.SCANCODE_MASK,
        F19 = (int)ScanCode.SCANCODE_F19 | InputConstants.SCANCODE_MASK,
        F20 = (int)ScanCode.SCANCODE_F20 | InputConstants.SCANCODE_MASK,
        F21 = (int)ScanCode.SCANCODE_F21 | InputConstants.SCANCODE_MASK,
        F22 = (int)ScanCode.SCANCODE_F22 | InputConstants.SCANCODE_MASK,
        F23 = (int)ScanCode.SCANCODE_F23 | InputConstants.SCANCODE_MASK,
        F24 = (int)ScanCode.SCANCODE_F24 | InputConstants.SCANCODE_MASK,
        EXECUTE = (int)ScanCode.SCANCODE_EXECUTE | InputConstants.SCANCODE_MASK,
        HELP = (int)ScanCode.SCANCODE_HELP | InputConstants.SCANCODE_MASK,
        MENU = (int)ScanCode.SCANCODE_MENU | InputConstants.SCANCODE_MASK,
        SELECT = (int)ScanCode.SCANCODE_SELECT | InputConstants.SCANCODE_MASK,
        STOP = (int)ScanCode.SCANCODE_STOP | InputConstants.SCANCODE_MASK,
        AGAIN = (int)ScanCode.SCANCODE_AGAIN | InputConstants.SCANCODE_MASK,
        UNDO = (int)ScanCode.SCANCODE_UNDO | InputConstants.SCANCODE_MASK,
        CUT = (int)ScanCode.SCANCODE_CUT | InputConstants.SCANCODE_MASK,
        COPY = (int)ScanCode.SCANCODE_COPY | InputConstants.SCANCODE_MASK,
        PASTE = (int)ScanCode.SCANCODE_PASTE | InputConstants.SCANCODE_MASK,
        FIND = (int)ScanCode.SCANCODE_FIND | InputConstants.SCANCODE_MASK,
        MUTE = (int)ScanCode.SCANCODE_MUTE | InputConstants.SCANCODE_MASK,
        VOLUMEUP = (int)ScanCode.SCANCODE_VOLUMEUP | InputConstants.SCANCODE_MASK,
        VOLUMEDOWN = (int)ScanCode.SCANCODE_VOLUMEDOWN | InputConstants.SCANCODE_MASK,
        KP_COMMA = (int)ScanCode.SCANCODE_KP_COMMA | InputConstants.SCANCODE_MASK,
        KP_EQUALSAS400 =
        (int)ScanCode.SCANCODE_KP_EQUALSAS400 | InputConstants.SCANCODE_MASK,

        ALTERASE = (int)ScanCode.SCANCODE_ALTERASE | InputConstants.SCANCODE_MASK,
        SYSREQ = (int)ScanCode.SCANCODE_SYSREQ | InputConstants.SCANCODE_MASK,
        CANCEL = (int)ScanCode.SCANCODE_CANCEL | InputConstants.SCANCODE_MASK,
        CLEAR = (int)ScanCode.SCANCODE_CLEAR | InputConstants.SCANCODE_MASK,
        PRIOR = (int)ScanCode.SCANCODE_PRIOR | InputConstants.SCANCODE_MASK,
        RETURN2 = (int)ScanCode.SCANCODE_RETURN2 | InputConstants.SCANCODE_MASK,
        SEPARATOR = (int)ScanCode.SCANCODE_SEPARATOR | InputConstants.SCANCODE_MASK,
        OUT = (int)ScanCode.SCANCODE_OUT | InputConstants.SCANCODE_MASK,
        OPER = (int)ScanCode.SCANCODE_OPER | InputConstants.SCANCODE_MASK,
        CLEARAGAIN = (int)ScanCode.SCANCODE_CLEARAGAIN | InputConstants.SCANCODE_MASK,
        CRSEL = (int)ScanCode.SCANCODE_CRSEL | InputConstants.SCANCODE_MASK,
        EXSEL = (int)ScanCode.SCANCODE_EXSEL | InputConstants.SCANCODE_MASK,

        KP_00 = (int)ScanCode.SCANCODE_KP_00 | InputConstants.SCANCODE_MASK,
        KP_000 = (int)ScanCode.SCANCODE_KP_000 | InputConstants.SCANCODE_MASK,
        THOUSANDSSEPARATOR =
        (int)ScanCode.SCANCODE_THOUSANDSSEPARATOR | InputConstants.SCANCODE_MASK,
        DECIMALSEPARATOR =
        (int)ScanCode.SCANCODE_DECIMALSEPARATOR | InputConstants.SCANCODE_MASK,
        CURRENCYUNIT = (int)ScanCode.SCANCODE_CURRENCYUNIT | InputConstants.SCANCODE_MASK,
        CURRENCYSUBUNIT =
        (int)ScanCode.SCANCODE_CURRENCYSUBUNIT | InputConstants.SCANCODE_MASK,
        KP_LEFTPAREN = (int)ScanCode.SCANCODE_KP_LEFTPAREN | InputConstants.SCANCODE_MASK,
        KP_RIGHTPAREN = (int)ScanCode.SCANCODE_KP_RIGHTPAREN | InputConstants.SCANCODE_MASK,
        KP_LEFTBRACE = (int)ScanCode.SCANCODE_KP_LEFTBRACE | InputConstants.SCANCODE_MASK,
        KP_RIGHTBRACE = (int)ScanCode.SCANCODE_KP_RIGHTBRACE | InputConstants.SCANCODE_MASK,
        KP_TAB = (int)ScanCode.SCANCODE_KP_TAB | InputConstants.SCANCODE_MASK,
        KP_BACKSPACE = (int)ScanCode.SCANCODE_KP_BACKSPACE | InputConstants.SCANCODE_MASK,
        KP_A = (int)ScanCode.SCANCODE_KP_A | InputConstants.SCANCODE_MASK,
        KP_B = (int)ScanCode.SCANCODE_KP_B | InputConstants.SCANCODE_MASK,
        KP_C = (int)ScanCode.SCANCODE_KP_C | InputConstants.SCANCODE_MASK,
        KP_D = (int)ScanCode.SCANCODE_KP_D | InputConstants.SCANCODE_MASK,
        KP_E = (int)ScanCode.SCANCODE_KP_E | InputConstants.SCANCODE_MASK,
        KP_F = (int)ScanCode.SCANCODE_KP_F | InputConstants.SCANCODE_MASK,
        KP_XOR = (int)ScanCode.SCANCODE_KP_XOR | InputConstants.SCANCODE_MASK,
        KP_POWER = (int)ScanCode.SCANCODE_KP_POWER | InputConstants.SCANCODE_MASK,
        KP_PERCENT = (int)ScanCode.SCANCODE_KP_PERCENT | InputConstants.SCANCODE_MASK,
        KP_LESS = (int)ScanCode.SCANCODE_KP_LESS | InputConstants.SCANCODE_MASK,
        KP_GREATER = (int)ScanCode.SCANCODE_KP_GREATER | InputConstants.SCANCODE_MASK,
        KP_AMPERSAND = (int)ScanCode.SCANCODE_KP_AMPERSAND | InputConstants.SCANCODE_MASK,
        KP_DBLAMPERSAND =
        (int)ScanCode.SCANCODE_KP_DBLAMPERSAND | InputConstants.SCANCODE_MASK,
        KP_VERTICALBAR =
        (int)ScanCode.SCANCODE_KP_VERTICALBAR | InputConstants.SCANCODE_MASK,
        KP_DBLVERTICALBAR =
        (int)ScanCode.SCANCODE_KP_DBLVERTICALBAR | InputConstants.SCANCODE_MASK,
        KP_COLON = (int)ScanCode.SCANCODE_KP_COLON | InputConstants.SCANCODE_MASK,
        KP_HASH = (int)ScanCode.SCANCODE_KP_HASH | InputConstants.SCANCODE_MASK,
        KP_SPACE = (int)ScanCode.SCANCODE_KP_SPACE | InputConstants.SCANCODE_MASK,
        KP_AT = (int)ScanCode.SCANCODE_KP_AT | InputConstants.SCANCODE_MASK,
        KP_EXCLAM = (int)ScanCode.SCANCODE_KP_EXCLAM | InputConstants.SCANCODE_MASK,
        KP_MEMSTORE = (int)ScanCode.SCANCODE_KP_MEMSTORE | InputConstants.SCANCODE_MASK,
        KP_MEMRECALL = (int)ScanCode.SCANCODE_KP_MEMRECALL | InputConstants.SCANCODE_MASK,
        KP_MEMCLEAR = (int)ScanCode.SCANCODE_KP_MEMCLEAR | InputConstants.SCANCODE_MASK,
        KP_MEMADD = (int)ScanCode.SCANCODE_KP_MEMADD | InputConstants.SCANCODE_MASK,
        KP_MEMSUBTRACT =
        (int)ScanCode.SCANCODE_KP_MEMSUBTRACT | InputConstants.SCANCODE_MASK,
        KP_MEMMULTIPLY =
        (int)ScanCode.SCANCODE_KP_MEMMULTIPLY | InputConstants.SCANCODE_MASK,
        KP_MEMDIVIDE = (int)ScanCode.SCANCODE_KP_MEMDIVIDE | InputConstants.SCANCODE_MASK,
        KP_PLUSMINUS = (int)ScanCode.SCANCODE_KP_PLUSMINUS | InputConstants.SCANCODE_MASK,
        KP_CLEAR = (int)ScanCode.SCANCODE_KP_CLEAR | InputConstants.SCANCODE_MASK,
        KP_CLEARENTRY = (int)ScanCode.SCANCODE_KP_CLEARENTRY | InputConstants.SCANCODE_MASK,
        KP_BINARY = (int)ScanCode.SCANCODE_KP_BINARY | InputConstants.SCANCODE_MASK,
        KP_OCTAL = (int)ScanCode.SCANCODE_KP_OCTAL | InputConstants.SCANCODE_MASK,
        KP_DECIMAL = (int)ScanCode.SCANCODE_KP_DECIMAL | InputConstants.SCANCODE_MASK,
        KP_HEXADECIMAL =
        (int)ScanCode.SCANCODE_KP_HEXADECIMAL | InputConstants.SCANCODE_MASK,

        LCTRL = (int)ScanCode.SCANCODE_LCTRL | InputConstants.SCANCODE_MASK,
        LSHIFT = (int)ScanCode.SCANCODE_LSHIFT | InputConstants.SCANCODE_MASK,
        LALT = (int)ScanCode.SCANCODE_LALT | InputConstants.SCANCODE_MASK,
        LGUI = (int)ScanCode.SCANCODE_LGUI | InputConstants.SCANCODE_MASK,
        RCTRL = (int)ScanCode.SCANCODE_RCTRL | InputConstants.SCANCODE_MASK,
        RSHIFT = (int)ScanCode.SCANCODE_RSHIFT | InputConstants.SCANCODE_MASK,
        RALT = (int)ScanCode.SCANCODE_RALT | InputConstants.SCANCODE_MASK,
        RGUI = (int)ScanCode.SCANCODE_RGUI | InputConstants.SCANCODE_MASK,

        MODE = (int)ScanCode.SCANCODE_MODE | InputConstants.SCANCODE_MASK,

        AUDIONEXT = (int)ScanCode.SCANCODE_AUDIONEXT | InputConstants.SCANCODE_MASK,
        AUDIOPREV = (int)ScanCode.SCANCODE_AUDIOPREV | InputConstants.SCANCODE_MASK,
        AUDIOSTOP = (int)ScanCode.SCANCODE_AUDIOSTOP | InputConstants.SCANCODE_MASK,
        AUDIOPLAY = (int)ScanCode.SCANCODE_AUDIOPLAY | InputConstants.SCANCODE_MASK,
        AUDIOMUTE = (int)ScanCode.SCANCODE_AUDIOMUTE | InputConstants.SCANCODE_MASK,
        MEDIASELECT = (int)ScanCode.SCANCODE_MEDIASELECT | InputConstants.SCANCODE_MASK,
        WWW = (int)ScanCode.SCANCODE_WWW | InputConstants.SCANCODE_MASK,
        MAIL = (int)ScanCode.SCANCODE_MAIL | InputConstants.SCANCODE_MASK,
        CALCULATOR = (int)ScanCode.SCANCODE_CALCULATOR | InputConstants.SCANCODE_MASK,
        COMPUTER = (int)ScanCode.SCANCODE_COMPUTER | InputConstants.SCANCODE_MASK,
        AC_SEARCH = (int)ScanCode.SCANCODE_AC_SEARCH | InputConstants.SCANCODE_MASK,
        AC_HOME = (int)ScanCode.SCANCODE_AC_HOME | InputConstants.SCANCODE_MASK,
        AC_BACK = (int)ScanCode.SCANCODE_AC_BACK | InputConstants.SCANCODE_MASK,
        AC_FORWARD = (int)ScanCode.SCANCODE_AC_FORWARD | InputConstants.SCANCODE_MASK,
        AC_STOP = (int)ScanCode.SCANCODE_AC_STOP | InputConstants.SCANCODE_MASK,
        AC_REFRESH = (int)ScanCode.SCANCODE_AC_REFRESH | InputConstants.SCANCODE_MASK,
        AC_BOOKMARKS = (int)ScanCode.SCANCODE_AC_BOOKMARKS | InputConstants.SCANCODE_MASK,

        BRIGHTNESSDOWN =
        (int)ScanCode.SCANCODE_BRIGHTNESSDOWN | InputConstants.SCANCODE_MASK,
        BRIGHTNESSUP = (int)ScanCode.SCANCODE_BRIGHTNESSUP | InputConstants.SCANCODE_MASK,
        DISPLAYSWITCH = (int)ScanCode.SCANCODE_DISPLAYSWITCH | InputConstants.SCANCODE_MASK,
        KBDILLUMTOGGLE =
        (int)ScanCode.SCANCODE_KBDILLUMTOGGLE | InputConstants.SCANCODE_MASK,
        KBDILLUMDOWN = (int)ScanCode.SCANCODE_KBDILLUMDOWN | InputConstants.SCANCODE_MASK,
        KBDILLUMUP = (int)ScanCode.SCANCODE_KBDILLUMUP | InputConstants.SCANCODE_MASK,
        EJECT = (int)ScanCode.SCANCODE_EJECT | InputConstants.SCANCODE_MASK,
        SLEEP = (int)ScanCode.SCANCODE_SLEEP | InputConstants.SCANCODE_MASK
    }
}
